# Generated by Django 2.2.1 on 2019-11-20 23:34

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20191121_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='comment',
            field=models.CharField(max_length=255, null=True, verbose_name=reviews.models.Answer),
        ),
    ]
