# Generated by Django 2.2.1 on 2019-11-20 23:51

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20191121_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.CharField(max_length=255, null=True, verbose_name=reviews.models.Answer),
        ),
    ]
