# Generated by Django 2.2.1 on 2019-11-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20191121_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reviews.Answer'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
