# Generated by Django 2.2.1 on 2019-11-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20191121_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenassessment',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='takenassessment',
            name='remark',
            field=models.CharField(default='Excellent', max_length=120),
        ),
    ]
